---
baseURL: https://interp.blog/
defaultContentLanguage: ko
languageCode: ko-kr
title: InterP Blog
theme: paper-mod
sectionPagesMenu: main
googleAnalytics: UA-126809878-1
metaDataFormat: yaml
summaryLength: 60
params:
  defaultTheme: light
  ShowPostNavLinks: true
  homeInfoParams:
    Title: InterP Blog ðŸ
    Content: things I'm interested in
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  author:
  - InterP
  cover:
    relative: true
  mainSections:
  - tech
  - essay
  - review
outputs:
  home:
  - HTML
  - RSS
  - JSON
menu:
  main:
  - url: "/review/"
    name: Review
    weight: 2
    identifier: review
  - url: "/essay/"
    name: Essay
    weight: 3
    identifier: essay
  - url: "/tech/"
    name: Tech
    weight: 1
    identifier: tech
pygmentsCodefences: true
pygmentsStyle: monokai
markup:
  goldmark:
    renderer:
      unsafe: true

module:
  # uncomment line below for temporary local development of module
  # replacements: "github.com/CaiJimmy/hugo-theme-stack/v3 -> ../../hugo-theme-stack"
  imports:
    - path: github.com/CaiJimmy/hugo-theme-stack/v3
      disable: false